version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      time: "04:00"
      timezone: Europe/Berlin
    allow:
      - dependency-type: 'production'
    target-branch: "dependencyAutoUpdate"
    open-pull-requests-limit: 20
    assignees:
      - DutchmanNL
    versioning-strategy: increase
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'cron'
      timezone: 'Europe/Berlin'
      cronjob: '44 2 23 * *'
    open-pull-requests-limit: 15
