/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "add device": {                                  "en": "add device",                                      "de": "Gerät hinzufügen",                                "ru": "добавить устройство",                             "pt": "Adicionar Dispositivo",                           "nl": "Voeg toestel toe",                                "fr": "ajouter un appareil",                             "it": "Aggiungi dispositivo",                            "es": "añadir dispositivo",                              "pl": "Dodaj urządzenie",                                "zh-cn": "添加设备"},
    "check input": {                                 "en": "check input",                                     "de": "Eingabe überprüfen",                              "ru": "проверить ввод",                                  "pt": "verificar entrada",                               "nl": "controleer invoer",                               "fr": "vérifier l'entrée",                               "it": "controllare l'input",                             "es": "comprobar entrada",                               "pl": "sprawdź dane wejściowe",                          "zh-cn": "检查输入"},
    "device-reminder adapter settings": {            "en": "Adapter settings for device-reminder",            "de": "Adaptereinstellungen für device-reminder",        "ru": "Настройки адаптера для device-reminder",          "pt": "Configurações do adaptador para device-reminder", "nl": "Adapterinstellingen voor device-reminder",        "fr": "Paramètres d'adaptateur pour device-reminder",    "it": "Impostazioni dell'adattatore per device-reminder", "es": "Ajustes del adaptador para device-reminder",      "pl": "Ustawienia adaptera dla device-reminder",         "zh-cn": "device-reminder的适配器设置"},
    "option1": {                                     "en": "option1",                                         "de": "Option 1",                                        "ru": "Опция 1",                                         "pt": "Opção 1",                                         "nl": "Optie 1",                                         "fr": "Option 1",                                        "it": "opzione 1",                                       "es": "Opción 1",                                        "pl": "opcja 1",                                         "zh-cn": "选项1"},
    "option2": {                                     "en": "option2",                                         "de": "Option 2",                                        "ru": "option2",                                         "pt": "opção 2",                                         "nl": "Optie 2",                                         "fr": "Option 2",                                        "it": "opzione 2",                                       "es": "opcion 2",                                        "pl": "Opcja 2",                                         "zh-cn": "选项2"},
    "help": {                                        "en": "help",                                            "de": "Hilfe",                                           "ru": "Помогите",                                        "pt": "Socorro",                                         "nl": "helpen",                                          "fr": "Aidez-moi",                                       "it": "Aiuto",                                           "es": "ayuda",                                           "pl": "Wsparcie",                                        "zh-cn": "救命"},
    "create device": {                               "en": "create device",                                   "de": "Gerät erstellen",                                 "ru": "создать устройство",                              "pt": "criar dispositivo",                               "nl": "maak apparaat",                                   "fr": "créer un appareil",                               "it": "crea dispositivo",                                "es": "crear dispositivo",                               "pl": "utwórz urządzenie",                               "zh-cn": "创建设备"},
    "device name": {                                 "en": "device name",                                     "de": "Gerätename",                                      "ru": "имя устройства",                                  "pt": "nome do dispositivo",                             "nl": "toestelnaam",                                     "fr": "nom de l'appareil",                               "it": "nome del dispositivo",                            "es": "nombre del dispositivo",                          "pl": "Nazwa urządzenia",                                "zh-cn": "设备名称"},
    "device type": {                                 "en": "device type",                                     "de": "Gerätetyp",                                       "ru": "тип устройства",                                  "pt": "tipo de dispositivo",                             "nl": "soort apparaat",                                  "fr": "type d'appareil",                                 "it": "tipo di dispositivo",                             "es": "tipo de dispositivo",                             "pl": "rodzaj urządzenia",                               "zh-cn": "设备类型"},
    "path consumption/energy": {                     "en": "path consumption/energy",                         "de": "Pfadverbrauch / Energie",                         "ru": "потребление пути / энергия",                      "pt": "consumo de caminho / energia",                    "nl": "pad verbruik / energie",                          "fr": "consommation de chemin / énergie",                "it": "consumo di percorso / energia",                   "es": "consumo de ruta / energía",                       "pl": "zużycie / energia ścieżki",                       "zh-cn": "路径消耗/能量"},
    "path switch on/off": {                          "en": "path switch on/off",                              "de": "Pfadschalter ein / aus",                          "ru": "включение / выключение пути",                     "pt": "interruptor de caminho ligado / desligado",       "nl": "pad schakelaar aan / uit",                        "fr": "allumer / éteindre le chemin",                    "it": "interruttore di percorso on / off",               "es": "interruptor de ruta encendido / apagado",         "pl": "włączanie / wyłączanie ścieżki",                  "zh-cn": "路径开关"},
    "starttext": {                                   "en": "starttext",                                       "de": "Starttext",                                       "ru": "starttext",                                       "pt": "texto inicial",                                   "nl": "starttekst",                                      "fr": "texte de départ",                                 "it": "starttext",                                       "es": "starttext",                                       "pl": "tekst startowy",                                  "zh-cn": "起始文本"},
    "endtext": {                                     "en": "endtext",                                         "de": "Endtext",                                         "ru": "конец текста",                                    "pt": "texto final",                                     "nl": "endtext",                                         "fr": "fin de texte",                                    "it": "endtext",                                         "es": "endtext",                                         "pl": "tekst końcowy",                                   "zh-cn": "结束语"},
};